server:
  port: 8081

spring:
  application:
    name: product-command-service
  sql:
    init:
      mode: always

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/command_db
    username: command_db_user
    password: command_db_password

    # Connection pool configuration
    hikari:
      connection-timeout: 600000 # 10 minutes
      maximum-pool-size: 3       # Connection limit
      auto-commit: false         # Let us handle transactions
      idle-timeout: 1800000      # 30 minutes
      minimum-idle: 2            # Minimum number of idle connections in the pool

  # JPA configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

    # Kafka configuration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all # Behavior for replica
        retries: 10 # Max retries
        retry.backoff.ms: 1000

    topics:
      product: product-event-topic
